### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by devpatocld**

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey pato, thanks for the suggestions here. generally speaking i think we should avoid adding too much content on an organization page, as the intent is to be an entryway into the projects, including the pinned projects, and looking through the rest that are available, not necessarilly for taking them off-site

im also wondering if we should have a little bit different of a banner, as if this will be used on "official" cloudinary organizations, we dont want to visually give that potential impression, which the banner is the first thing you see

aside from the banner, perhaps something like this could be more appropriate?

---

Cloudinary Community

<div align="center">
  <a href="https://cloudinary.com/" target="_blank">Cloudinary</a>
    <span>&nbsp;&bull;&nbsp;</span>
  <a href="https://twitter.com/cloudinary" target="_blank">Twitter</a>
    <span>&nbsp;&bull;&nbsp;</span>
  <a href="https://cloudinary.com/documentation" target="_blank">Docs</a>
    <span>&nbsp;&bull;&nbsp;</span>
  <a href="https://cloudinary.com/blog/" target="_blank">Blog</a>
    <span>&nbsp;&bull;&nbsp;</span>
  <a href="https://community.cloudinary.com/" target="_blank">Community</a>
  <br />
</div>

<br />

This organization is maintained by the developer community supported by the Cloudinary Developer Experience team. The projects and libraries are considered community projects and do not indicate official Cloudinary support.

**Contribute**

Interested in contributing to a project? Find the CONTRIBUTING file in the community project to learn how. Interested in creating a new project? Reach out to devrel@cloudinary.com and let us know what you had in mind!

**More from Cloudinary**

- [Cloudinary GitHub](https://github.com/cloudinary): Official Cloudinary organization for all the libraries, SDKs, and APIs.
- [Cloudinary Devs](https://github.com/cloudinary-devs): Examples, demos, and workshop materials directly from the Cloudinary team.

**Community**

Engage in collaborative coding, connect with fellow enthusiasts, and gather insights from a vibrant open-source network over on [Twitter](https://twitter.com/cloudinary), [Discord](https://discord.gg/cloudinary), or the [Community Forums](https://community.cloudinary.com/)

**Comment by devpatocld** [comment]
> hey pato, thanks for the suggestions here. generally speaking i think we should avoid adding too much content on an organization page, as the intent is to be an entryway into the projects, including the pinned projects, and looking through the rest that are available, not necessarilly for taking them off-site
> 
> im also wondering if we should have a little bit different of a banner, as if this will be used on "official" cloudinary organizations, we dont want to visually give that potential impression, which the banner is the first thing you see
> 
> aside from the banner, perhaps something like this could be more appropriate?
> 
> Cloudinary Community
> 
> [Cloudinary](https://cloudinary.com/)  •  [Twitter](https://twitter.com/cloudinary)  •  [Docs](https://cloudinary.com/documentation)  •  [Blog](https://cloudinary.com/blog/)  •  [Community](https://community.cloudinary.com/)
> 
> This organization is maintained by the developer community supported by the Cloudinary Developer Experience team. The projects and libraries are considered community projects and do not indicate official Cloudinary support.
> 
> **Contribute**
> 
> Interested in contributing to a project? Find the CONTRIBUTING file in the community project to learn how. Interested in creating a new project? Reach out to [devrel@cloudinary.com](mailto:devrel@cloudinary.com) and let us know what you had in mind!
> 
> **More from Cloudinary**
> 
> * [Cloudinary GitHub](https://github.com/cloudinary): Official Cloudinary organization for all the libraries, SDKs, and APIs.
> * [Cloudinary Devs](https://github.com/cloudinary-devs): Examples, demos, and workshop materials directly from the Cloudinary team.
> 
> **Community**
> 
> Engage in collaborative coding, connect with fellow enthusiasts, and gather insights from a vibrant open-source network over on [Twitter](https://twitter.com/cloudinary), [Discord](https://discord.gg/cloudinary), or the [Community Forums](https://community.cloudinary.com/)

**Comment by devpatocld** [comment]
> Discord

**Comment by devpatocld** [comment]
> hey pato, thanks for the suggestions here. generally speaking i think we should avoid adding too much content on an organization page, as the intent is to be an entryway into the projects, including the pinned projects, and looking through the rest that are available, not necessarilly for taking them off-site
> 
> im also wondering if we should have a little bit different of a banner, as if this will be used on "official" cloudinary organizations, we dont want to visually give that potential impression, which the banner is the first thing you see
> 
> aside from the banner, perhaps something like this could be more appropriate?
> 
> Cloudinary Community
> 
> [Cloudinary](https://cloudinary.com/)  •  [Twitter](https://twitter.com/cloudinary)  •  [Docs](https://cloudinary.com/documentation)  •  [Blog](https://cloudinary.com/blog/)  •  [Community](https://community.cloudinary.com/)
> 
> This organization is maintained by the developer community supported by the Cloudinary Developer Experience team. The projects and libraries are considered community projects and do not indicate official Cloudinary support.
> 
> **Contribute**
> 
> Interested in contributing to a project? Find the CONTRIBUTING file in the community project to learn how. Interested in creating a new project? Reach out to [devrel@cloudinary.com](mailto:devrel@cloudinary.com) and let us know what you had in mind!
> 
> **More from Cloudinary**
> 
> * [Cloudinary GitHub](https://github.com/cloudinary): Official Cloudinary organization for all the libraries, SDKs, and APIs.
> * [Cloudinary Devs](https://github.com/cloudinary-devs): Examples, demos, and workshop materials directly from the Cloudinary team.
> 
> **Community**
> 
> Engage in collaborative coding, connect with fellow enthusiasts, and gather insights from a vibrant open-source network over on [Twitter](https://twitter.com/cloudinary), [Discord](https://discord.gg/cloudinary), or the [Community Forums](https://community.cloudinary.com/)

**Pull request closed without merging**
